/**
 * Daily motivational quotes — French + translations.
 * Rotated by day-of-year in the MotivationStrip component.
 */
export const MOTIVATION_QUOTES: readonly {
  fr: string;
  zh: string;
  en: string;
  ar: string;
  author: string;
}[] = [
  {
    fr: "Impossible n'est pas français.",
    zh: "在法语里没有「不可能」。",
    en: "'Impossible' is not French.",
    ar: "المستحيل ليس فرنسياً.",
    author: "Napoléon",
  },
  {
    fr: "La victoire appartient au plus persévérant.",
    zh: "胜利属于最坚持的人。",
    en: "Victory belongs to the most persistent.",
    ar: "النصر لمن يثابر أكثر.",
    author: "Napoléon",
  },
  {
    fr: "Au milieu de l'hiver, j'ai découvert en moi un invincible été.",
    zh: "隆冬之中，我发现内心有一个不可战胜的夏天。",
    en: "In the midst of winter, I found within me an invincible summer.",
    ar: "في عمق الشتاء، اكتشفت في داخلي صيفاً لا يُقهر.",
    author: "Camus",
  },
  {
    fr: "De l'audace, encore de l'audace, toujours de l'audace !",
    zh: "大胆！再大胆！永远大胆！",
    en: "Audacity, more audacity, always audacity!",
    ar: "الجرأة، مزيداً من الجرأة، دائماً الجرأة!",
    author: "Danton",
  },
  {
    fr: "Même la nuit la plus sombre prendra fin et le soleil se lèvera.",
    zh: "即使最黑暗的夜也终将过去，太阳照常升起。",
    en: "Even the darkest night will end and the sun will rise.",
    ar: "حتى أحلك الليالي ستنتهي وستشرق الشمس.",
    author: "Hugo",
  },
  {
    fr: "L'avenir est une porte, le passé en est la clé.",
    zh: "未来是一扇门，过去是钥匙。",
    en: "The future is a door, the past is the key.",
    ar: "المستقبل باب، والماضي مفتاحه.",
    author: "Hugo",
  },
  {
    fr: "Persévérez, c'est le secret de tous les triomphes.",
    zh: "坚持，是一切胜利的秘诀。",
    en: "Persevere — that is the secret of all triumphs.",
    ar: "المثابرة هي سر كل انتصار.",
    author: "Hugo",
  },
  {
    fr: "Fais de ta vie un rêve, et d'un rêve, une réalité.",
    zh: "让生活成为梦想，让梦想成为现实。",
    en: "Make your life a dream, and a dream, a reality.",
    ar: "اجعل حياتك حلماً، واجعل الحلم حقيقة.",
    author: "Saint-Exupéry",
  },
  {
    fr: "Ce qui ne me tue pas me rend plus fort.",
    zh: "凡杀不死我的，使我更强。",
    en: "What does not kill me makes me stronger.",
    ar: "ما لا يقتلني يجعلني أقوى.",
    author: "Nietzsche",
  },
  {
    fr: "Celui qui a un pourquoi peut supporter presque n'importe quel comment.",
    zh: "知道为什么而活的人，几乎能承受任何活法。",
    en: "He who has a why can bear almost any how.",
    ar: "من لديه سبب للعيش يمكنه تحمّل أي طريقة للعيش.",
    author: "Nietzsche",
  },
  {
    fr: "Le succès n'est pas final, l'échec n'est pas fatal : c'est le courage de continuer qui compte.",
    zh: "成功不是终点，失败不是终结，唯有继续前行的勇气才最重要。",
    en: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    ar: "النجاح ليس نهائياً، والفشل ليس قاتلاً: الشجاعة للاستمرار هي ما يهم.",
    author: "Churchill",
  },
  {
    fr: "Le succès, c'est d'aller d'échec en échec sans perdre son enthousiasme.",
    zh: "成功就是从一个失败走向另一个失败，而不丧失热情。",
    en: "Success is going from failure to failure without losing enthusiasm.",
    ar: "النجاح هو الانتقال من فشل إلى فشل دون فقدان الحماس.",
    author: "Churchill",
  },
  {
    fr: "Je ne perds jamais. Soit je gagne, soit j'apprends.",
    zh: "我从不失败。要么赢，要么学到东西。",
    en: "I never lose. I either win or learn.",
    ar: "لا أخسر أبداً. إما أفوز أو أتعلم.",
    author: "Mandela",
  },
  {
    fr: "Cela semble toujours impossible jusqu'à ce que ce soit fait.",
    zh: "在事情做成之前，一切看起来都不可能。",
    en: "It always seems impossible until it's done.",
    ar: "يبدو الأمر مستحيلاً دائماً حتى يتم إنجازه.",
    author: "Mandela",
  },
  {
    fr: "Un voyage de mille lieues commence toujours par un premier pas.",
    zh: "千里之行，始于足下。",
    en: "A journey of a thousand leagues begins with a single step.",
    ar: "رحلة الألف ميل تبدأ بخطوة واحدة.",
    author: "Lao Tseu",
  },
  {
    fr: "Celui qui déplace la montagne commence par déplacer de petites pierres.",
    zh: "移山者，始于搬小石。",
    en: "The man who moves a mountain begins by carrying small stones.",
    ar: "من ينقل الجبل يبدأ بنقل الحجارة الصغيرة.",
    author: "Confucius",
  },
  {
    fr: "Tomber sept fois, se relever huit.",
    zh: "七次跌倒，八次站起。",
    en: "Fall seven times, stand up eight.",
    ar: "اسقط سبع مرات، انهض ثماني.",
    author: "Proverbe japonais",
  },
  {
    fr: "La chance ne sourit qu'aux esprits bien préparés.",
    zh: "机遇只青睐有准备的人。",
    en: "Fortune favors the prepared mind.",
    ar: "الحظ لا يبتسم إلا للعقول المستعدة.",
    author: "Pasteur",
  },
  {
    fr: "La persévérance est la noblesse de l'obstination.",
    zh: "坚持是执着的高贵形式。",
    en: "Perseverance is the nobility of obstinacy.",
    ar: "المثابرة هي النبل في العناد.",
    author: "Balzac",
  },
  {
    fr: "Il n'existe pas de grande tâche difficile qui ne puisse être décomposée en petites tâches faciles.",
    zh: "再大的难事，都能拆成小的易事。",
    en: "No great difficult task cannot be broken into small easy ones.",
    ar: "لا توجد مهمة كبيرة صعبة لا يمكن تقسيمها إلى مهام صغيرة سهلة.",
    author: "Balzac",
  },
  {
    fr: "Ce n'est pas parce que les choses sont difficiles que nous n'osons pas, c'est parce que nous n'osons pas qu'elles sont difficiles.",
    zh: "不是因为难我们才不敢，而是因为不敢才觉得难。",
    en: "It is not because things are difficult that we do not dare; it is because we do not dare that they are difficult.",
    ar: "ليس لأن الأمور صعبة لا نجرؤ، بل لأننا لا نجرؤ تبدو صعبة.",
    author: "Sénèque",
  },
  {
    fr: "La chance, c'est ce qui arrive quand la préparation rencontre l'opportunité.",
    zh: "运气，就是准备遇上了机遇。",
    en: "Luck is what happens when preparation meets opportunity.",
    ar: "الحظ هو ما يحدث عندما يلتقي الاستعداد بالفرصة.",
    author: "Sénèque",
  },
  {
    fr: "Seuls ceux qui sont assez fous pour penser qu'ils peuvent changer le monde y parviennent.",
    zh: "只有疯狂到认为自己能改变世界的人，才能真正改变世界。",
    en: "Only those crazy enough to think they can change the world actually do.",
    ar: "فقط المجانين الذين يظنون أنهم يستطيعون تغيير العالم هم من يفعلون.",
    author: "Steve Jobs",
  },
  {
    fr: "Votre temps est limité, ne le gaspillez pas en vivant la vie d'un autre.",
    zh: "你的时间有限，别浪费在过别人的生活上。",
    en: "Your time is limited — don't waste it living someone else's life.",
    ar: "وقتك محدود، لا تضيّعه في عيش حياة شخص آخر.",
    author: "Steve Jobs",
  },
  {
    fr: "Dans la vie, rien n'est à craindre, tout est à comprendre.",
    zh: "生活中没有什么可怕的，只有需要理解的。",
    en: "In life, nothing is to be feared — everything is to be understood.",
    ar: "في الحياة، لا شيء يُخشى، كل شيء يُفهم.",
    author: "Marie Curie",
  },
  {
    fr: "Si vous me demandez ce que je suis venu faire en ce monde, je vous répondrai : je suis venu vivre à haute voix.",
    zh: "你若问我来此世间何为，我答：我来大声地活。",
    en: "If you ask what I came to do in this world, I will answer: I came to live out loud.",
    ar: "إن سألتموني لماذا جئت إلى هذا العالم، سأجيب: جئت لأعيش بصوت عالٍ.",
    author: "Zola",
  },
  {
    fr: "Il n'y a qu'un héroïsme au monde : voir le monde tel qu'il est et l'aimer.",
    zh: "世上只有一种英雄主义：看清生活真相后依然热爱它。",
    en: "There is only one heroism in the world: to see the world as it is, and to love it.",
    ar: "لا يوجد سوى بطولة واحدة في العالم: أن ترى العالم كما هو وتحبه.",
    author: "Romain Rolland",
  },
  {
    fr: "Toute la sagesse humaine est dans ces deux mots : attendre et espérer.",
    zh: "人类全部智慧凝于两个词：等待与希望。",
    en: "All human wisdom is in two words: wait and hope.",
    ar: "كل حكمة البشر في كلمتين: انتظر وارجُ.",
    author: "Dumas",
  },
  {
    fr: "Vouloir, c'est pouvoir.",
    zh: "有志者，事竟成。",
    en: "Where there's a will, there's a way.",
    ar: "من يُرد يستطع.",
    author: "Proverbe français",
  },
  {
    fr: "À cœur vaillant rien d'impossible.",
    zh: "勇者无惧，万事可成。",
    en: "For a valiant heart, nothing is impossible.",
    ar: "لا شيء مستحيل أمام القلب الشجاع.",
    author: "Proverbe français",
  },
  {
    fr: "Paris ne s'est pas fait en un jour.",
    zh: "罗马不是一天建成的。",
    en: "Paris was not built in a day.",
    ar: "لم تُبنَ باريس في يوم واحد.",
    author: "Proverbe français",
  },
  {
    fr: "Petit à petit, l'oiseau fait son nid.",
    zh: "一点一点，鸟儿筑成了巢。",
    en: "Little by little, the bird builds its nest.",
    ar: "شيئاً فشيئاً، يبني العصفور عشه.",
    author: "Proverbe français",
  },
  {
    fr: "La gloire se donne seulement à ceux qui l'ont toujours rêvée.",
    zh: "荣耀只属于始终心怀向往的人。",
    en: "Glory is given only to those who have always dreamed of it.",
    ar: "المجد لا يُمنح إلا لمن حلم به دائماً.",
    author: "de Gaulle",
  },
  {
    fr: "Le génie est un pour cent d'inspiration et quatre-vingt-dix-neuf pour cent de transpiration.",
    zh: "天才是百分之一的灵感加百分之九十九的汗水。",
    en: "Genius is one percent inspiration and ninety-nine percent perspiration.",
    ar: "العبقرية واحد بالمئة إلهام وتسعة وتسعون بالمئة عرق.",
    author: "Edison",
  },
  {
    fr: "L'éducation est l'arme la plus puissante pour changer le monde.",
    zh: "教育是改变世界最强大的武器。",
    en: "Education is the most powerful weapon to change the world.",
    ar: "التعليم هو أقوى سلاح لتغيير العالم.",
    author: "Mandela",
  },
  {
    fr: "L'avenir appartient à ceux qui croient en la beauté de leurs rêves.",
    zh: "未来属于相信梦想之美的人。",
    en: "The future belongs to those who believe in the beauty of their dreams.",
    ar: "المستقبل لمن يؤمن بجمال أحلامه.",
    author: "Eleanor Roosevelt",
  },
  {
    fr: "La folie, c'est de faire toujours la même chose et de s'attendre à un résultat différent.",
    zh: "疯狂就是重复同样的事却期待不同的结果。",
    en: "Insanity is doing the same thing over and over and expecting different results.",
    ar: "الجنون هو تكرار نفس الشيء وتوقع نتيجة مختلفة.",
    author: "Einstein",
  },
  {
    fr: "La discipline est le pont entre les objectifs et les résultats.",
    zh: "自律是目标与结果之间的桥梁。",
    en: "Discipline is the bridge between goals and results.",
    ar: "الانضباط هو الجسر بين الأهداف والنتائج.",
    author: "Jim Rohn",
  },
  {
    fr: "La route est longue, mais qui marche y arrivera.",
    zh: "路虽远，行则将至。",
    en: "The road is long, but those who walk will arrive.",
    ar: "الطريق طويل، لكن من يسير سيصل.",
    author: "Xunzi",
  },
  {
    fr: "Même face à des millions d'adversaires, j'avancerai.",
    zh: "虽千万人，吾往矣。",
    en: "Even facing millions of adversaries, I shall go forth.",
    ar: "حتى لو واجهت الملايين، سأمضي قُدماً.",
    author: "Mencius",
  },
  {
    fr: "Ce que l'on porte dans le cœur finit toujours par trouver écho.",
    zh: "念念不忘，必有回响。",
    en: "What you hold in your heart will always find its echo.",
    ar: "ما تحمله في قلبك سيجد صداه حتماً.",
    author: "Li Shutong",
  },
  {
    fr: "Tant qu'il reste un souffle, on allume une flamme.",
    zh: "有一口气，点一盏灯。",
    en: "As long as there is breath, light a flame.",
    ar: "ما دام هناك نَفَس، أشعل شعلة.",
    author: "Wong Kar-wai",
  },
  {
    fr: "Tu as le pouvoir sur ton esprit, pas sur les événements. Réalise cela, et tu trouveras la force.",
    zh: "你能掌控的是内心，而非事件。悟到这点，你就有了力量。",
    en: "You have power over your mind, not outside events. Realize this, and you will find strength.",
    ar: "لديك السيطرة على عقلك، لا على الأحداث. أدرك هذا وستجد القوة.",
    author: "Marc Aurèle",
  },
  {
    fr: "L'obstacle sur le chemin devient le chemin.",
    zh: "路上的障碍，本身就是路。",
    en: "The obstacle on the path becomes the path.",
    ar: "العائق في الطريق يصبح هو الطريق.",
    author: "Marc Aurèle",
  },
] as const;
