/**
 * Daily motivational quotes in French.
 * Rotated by day-of-year in the MotivationStrip component.
 */
export const MOTIVATION_QUOTES = [
  { fr: "Petit à petit, l'oiseau fait son nid." },
  { fr: "Le courage n'est pas l'absence de peur, c'est d'agir malgré elle." },
  { fr: "Chaque jour est une nouvelle chance de réussir." },
  { fr: "La persévérance est la clé du succès." },
  { fr: "Le succès est la somme de petits efforts répétés jour après jour." },
  { fr: "Il n'y a pas de raccourci vers un endroit qui en vaut la peine." },
  { fr: "La seule limite, c'est celle que vous vous fixez." },
  { fr: "Croyez en vous et tout devient possible." },
  { fr: "L'avenir appartient à ceux qui se lèvent tôt." },
  { fr: "Un voyage de mille lieues commence par un seul pas." },
  { fr: "Le savoir est la seule richesse qu'on peut donner sans s'appauvrir." },
  { fr: "Qui veut voyager loin ménage sa monture." },
  { fr: "La connaissance s'acquiert par l'expérience, tout le reste n'est que de l'information." },
  { fr: "Ce n'est pas parce que les choses sont difficiles que nous n'osons pas, c'est parce que nous n'osons pas qu'elles sont difficiles." },
  { fr: "La vie est un long fleuve tranquille pour celui qui sait nager." },
  { fr: "Après la pluie, le beau temps." },
  { fr: "Rien ne sert de courir, il faut partir à point." },
  { fr: "La meilleure façon de prédire l'avenir, c'est de le créer." },
  { fr: "Tout est possible à qui rêve, ose, travaille et n'abandonne jamais." },
  { fr: "On ne naît pas savant, on le devient." },
  { fr: "Chaque expert a d'abord été un débutant." },
  { fr: "L'échec est le fondement de la réussite." },
  { fr: "La patience est amère, mais son fruit est doux." },
  { fr: "Il faut toujours viser la lune, car même en cas d'échec, on atterrit dans les étoiles." },
  { fr: "Le plus grand voyage commence par un premier pas." },
  { fr: "La discipline est le pont entre les objectifs et les accomplissements." },
  { fr: "Soyez le changement que vous voulez voir dans le monde." },
  { fr: "La seule façon de faire du bon travail est d'aimer ce que vous faites." },
  { fr: "Les grandes choses ne sont jamais faites par une seule personne, elles sont faites par une équipe." },
  { fr: "Tout ce que l'esprit peut concevoir et croire, il peut le réaliser." },
  { fr: "Paris ne s'est pas fait en un jour." },
  { fr: "Vouloir, c'est pouvoir." },
  { fr: "La réussite n'est pas la clé du bonheur. Le bonheur est la clé de la réussite." },
  { fr: "À cœur vaillant rien d'impossible." },
  { fr: "Là où il y a une volonté, il y a un chemin." },
  { fr: "L'éducation est l'arme la plus puissante pour changer le monde." },
  { fr: "La lecture est à l'esprit ce que l'exercice est au corps." },
  { fr: "Apprendre une langue, c'est avoir une fenêtre de plus par laquelle regarder le monde." },
  { fr: "Plus vous en savez, plus vous réalisez que vous ne savez rien." },
  { fr: "Le doute est le commencement de la sagesse." },
  { fr: "Qui n'avance pas, recule." },
  { fr: "La pratique rend parfait." },
  { fr: "C'est en forgeant qu'on devient forgeron." },
  { fr: "L'impossible n'est pas français." },
  { fr: "Chaque question est un pas vers le Canada." },
  { fr: "Votre accent s'améliore chaque jour, continuez !" },
  { fr: "Le TCF n'est qu'une étape, vous êtes déjà sur le bon chemin." },
  { fr: "La grammaire est une chanson douce." },
  { fr: "Parler une langue, c'est adopter un monde." },
  { fr: "Ce qui compte, ce n'est pas le nombre de fois où l'on tombe, mais le nombre de fois où l'on se relève." },
] as const;
