"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Loader2, RefreshCw, Star, Volume2 } from "lucide-react";
import { useTranslations, useLocale } from "next-intl";
import { Popover, PopoverContent, PopoverAnchor } from "@/components/ui/popover";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { getVocabularyCard, regenerateVocabularyCard, logWordView } from "@/lib/api/vocabulary";
import { getCached, setCache, clearCache } from "@/lib/vocab-cache";
import { useFrenchSpeech } from "@/hooks/use-french-speech";
import { useAuthStore } from "@/stores/auth-store";
import { useVocabStore } from "@/stores/vocab-store";
import type { VocabularyCardData, ConjugationTable } from "@/lib/api/types";
import type { WordSaveContext } from "./french-text";

interface WordCardProps {
  word: string;
  anchorEl: HTMLElement;
  onClose: () => void;
  saveContext?: WordSaveContext;
  sentence?: string;
  sentenceTranslation?: string;
}

export function WordCard({ word: initialWord, anchorEl, onClose, saveContext, sentence, sentenceTranslation }: WordCardProps) {
  const t = useTranslations();
  const locale = useLocale();
  const isAuthenticated = useAuthStore((s) => s.isAuthenticated);
  const [currentWord, setCurrentWord] = useState(initialWord);
  const [data, setData] = useState<VocabularyCardData | null>(
    () => getCached(initialWord, locale) ?? null,
  );
  const [loading, setLoading] = useState(!data);
  const [error, setError] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [regenerating, setRegenerating] = useState(false);
  const { speak, playing } = useFrenchSpeech();

  const { isSaved, addWord, removeWord, isLoaded: vocabLoaded, fetchSavedWords } = useVocabStore();
  const wordSaved = vocabLoaded && isSaved(currentWord);
  const [starBounce, setStarBounce] = useState(false);

  // Load saved words on first mount if not loaded
  useEffect(() => {
    if (!vocabLoaded && isAuthenticated) {
      fetchSavedWords();
    }
  }, [vocabLoaded, isAuthenticated, fetchSavedWords]);

  const handleToggleSave = useCallback(() => {
    if (!isAuthenticated) return;
    const normalized = currentWord.trim().toLowerCase();
    if (isSaved(currentWord)) {
      removeWord(normalized);
      toast(t("wordCard.unsaved"), { duration: 1500 });
    } else {
      addWord(normalized, {
        word: normalized,
        source_type: saveContext?.sourceType,
        test_set_id: saveContext?.testSetId,
        test_set_name: saveContext?.testSetName,
        question_id: saveContext?.questionId,
        question_number: saveContext?.questionNumber,
        sentence,
      });
      setStarBounce(true);
      setTimeout(() => setStarBounce(false), 400);
      toast(t("wordCard.saved"), { duration: 1500 });
    }
  }, [isAuthenticated, currentWord, isSaved, addWord, removeWord, saveContext, sentence, t]);

  const handleRegenerate = useCallback(async () => {
    if (regenerating || loading) return;
    setRegenerating(true);
    setError(false);
    clearCache(currentWord, locale);
    try {
      const res = await regenerateVocabularyCard(currentWord, locale);
      setCache(currentWord, res, locale);
      setData(res);
    } catch {
      setError(true);
    } finally {
      setRegenerating(false);
    }
  }, [currentWord, locale, regenerating, loading]);

  useEffect(() => {
    // Check cache first
    const cached = getCached(currentWord, locale);
    if (cached) {
      setData(cached);
      setLoading(false);
      setError(false);
      setGenerating(false);
      logWordView(currentWord, saveContext?.sourceType ?? null).then((autoSaved) => {
        if (autoSaved) {
          fetchSavedWords();
          setStarBounce(true);
          setTimeout(() => setStarBounce(false), 400);
          toast(t("wordCard.autoSaved"), { duration: 2000 });
        }
      });
      return;
    }

    let cancelled = false;
    let retryTimer: ReturnType<typeof setTimeout>;
    setLoading(true);
    setError(false);
    setGenerating(false);
    setData(null);

    const fetchCard = (retries = 0) => {
      getVocabularyCard(currentWord, locale)
        .then((res) => {
          if (cancelled) return;
          setCache(currentWord, res, locale);
          setData(res);
          setGenerating(false);
          setLoading(false);
          logWordView(currentWord, saveContext?.sourceType ?? null).then((autoSaved) => {
            if (autoSaved) {
              fetchSavedWords();
              setStarBounce(true);
              setTimeout(() => setStarBounce(false), 400);
              toast(t("wordCard.autoSaved"), { duration: 2000 });
            }
          });
        })
        .catch((err) => {
          if (cancelled) return;
          // 409 = card is being generated by another request, retry
          const status = (err as { status?: number })?.status;
          if (status === 409 && retries < 15) {
            setGenerating(true);
            setLoading(true);
            retryTimer = setTimeout(() => fetchCard(retries + 1), 3000);
          } else {
            setError(true);
            setGenerating(false);
            setLoading(false);
          }
        });
    };

    fetchCard();

    return () => {
      cancelled = true;
      clearTimeout(retryTimer);
    };
  }, [currentWord, locale]);

  const handleSpeak = useCallback(() => {
    speak(currentWord, data?.audio_url);
  }, [speak, currentWord, data?.audio_url]);

  // Auto-play pronunciation when data is ready (especially from cache)
  const autoPlayedRef = useRef<string | null>(null);
  useEffect(() => {
    // Only auto-play when data matches current word (display_form check prevents stale audio)
    if (!loading && data && autoPlayedRef.current !== currentWord && data.display_form?.toLowerCase() === currentWord.toLowerCase()) {
      autoPlayedRef.current = currentWord;
      speak(currentWord, data.audio_url);
    }
  }, [loading, data, currentWord, speak]);

  const handleFamilyWordClick = useCallback((word: string) => {
    if (word !== currentWord) {
      setCurrentWord(word);
    }
  }, [currentWord]);

  // Match contextual sense against sentence translation
  const contextSense = useMemo(() => {
    if (!sentenceTranslation || !data?.senses?.length) return null;
    const trans = sentenceTranslation.toLowerCase();
    return data.senses.find((s) => {
      const native = s.native?.toLowerCase();
      const zh = s.zh?.toLowerCase();
      const en = s.en?.toLowerCase();
      return (native && trans.includes(native)) || (zh && trans.includes(zh)) || (en && trans.includes(en));
    }) ?? null;
  }, [sentenceTranslation, data?.senses]);

  // Gender color: blue for masculin, rose for féminin
  const genderColor =
    data?.gender === "masculin"
      ? "text-blue-600 dark:text-blue-400"
      : data?.gender === "féminin"
        ? "text-rose-600 dark:text-rose-400"
        : "";

  const isVerb = !!(data?.present || data?.passe_compose);
  const isAdj = !!data?.adjective_forms;

  // Clean up null-like values from backend
  const article = data?.article && data.article !== "null" ? data.article : null;
  const pluralForm = data?.plural_form && data.plural_form !== "null" ? data.plural_form : null;
  const pos = data?.part_of_speech && data.part_of_speech !== "OTHER" ? data.part_of_speech : null;

  // Resolve native meaning (prefer meaning_native, fall back to legacy fields)
  const nativeMeaning = data?.meaning_native
    || (locale === "zh" ? data?.meaning_zh : null)
    || (locale === "en" ? data?.meaning_en : null);

  // Word family label based on locale
  const familyLabel = data?.word_family
    ? (locale === "zh" ? data.word_family.label_zh : data.word_family.label_en)
    : null;

  return (
    <Popover open onOpenChange={(open) => !open && onClose()}>
      <PopoverAnchor virtualRef={{ current: anchorEl }} />
      <PopoverContent
        className={`max-h-[min(70vh,480px)] overflow-y-auto p-0 ${isVerb ? "w-[420px]" : "w-96"}`}
        side="bottom"
        align="start"
        collisionPadding={16}
        avoidCollisions
        onOpenAutoFocus={(e) => e.preventDefault()}
        onClick={(e) => e.stopPropagation()}
      >
        <div className="p-4 space-y-3">
          {loading ? (
            <WordCardLoading generating={generating} />
          ) : error ? (
            <div className="py-4 text-center text-sm text-muted-foreground">
              {t("wordCard.error")}
            </div>
          ) : data ? (
            <>
              {/* Header */}
              <div className="flex items-start justify-between gap-2">
                <div className="flex items-baseline gap-1.5">
                  {article && (
                    <span className={`text-sm ${genderColor}`}>
                      {article}
                    </span>
                  )}
                  <span className={`text-lg font-semibold ${genderColor || "text-foreground"}`}>
                    {data.display_form}
                  </span>
                </div>
                <div className="flex items-center gap-1.5">
                  <button
                    onClick={handleSpeak}
                    className="rounded-full p-1 hover:bg-muted transition-colors"
                    title={t("wordCard.pronunciation")}
                  >
                    <Volume2
                      className={`h-4 w-4 ${playing ? "text-blue-500 animate-pulse" : "text-muted-foreground"}`}
                    />
                  </button>
                  {isAuthenticated && (
                    <button
                      onClick={handleToggleSave}
                      className="rounded-full p-1 hover:bg-muted transition-colors"
                      title={wordSaved ? t("wordCard.unsave") : t("wordCard.save")}
                    >
                      <Star
                        className={`h-4 w-4 transition-transform ${wordSaved ? "fill-yellow-400 text-yellow-400" : "text-muted-foreground"} ${starBounce ? "scale-150" : "scale-100"}`}
                      />
                    </button>
                  )}
                  {isAuthenticated && data && (
                    <button
                      onClick={handleRegenerate}
                      disabled={regenerating}
                      className="rounded-full p-1 hover:bg-muted transition-colors"
                      title={t("wordCard.regenerate")}
                    >
                      <RefreshCw
                        className={`h-3.5 w-3.5 text-muted-foreground ${regenerating ? "animate-spin" : ""}`}
                      />
                    </button>
                  )}
                  {data.cefr_level && (
                    <Badge variant="secondary" className="text-[10px] px-1.5 py-0">
                      {data.cefr_level}
                    </Badge>
                  )}
                </div>
              </div>

              {/* IPA + POS + Gender */}
              <div className="flex flex-wrap items-center gap-2 text-xs text-muted-foreground">
                {data.ipa && <span className="font-mono">{data.ipa}</span>}
                {pos && (
                  <Badge variant="outline" className="text-[10px] px-1 py-0">
                    {pos}
                  </Badge>
                )}
                {data.gender && data.gender !== "null" && !(pos && /\.f[\.\b]|\.m[\.\b]|\.f$|\.m$/.test(pos)) && (
                  <span className={genderColor}>{data.gender}</span>
                )}
              </div>

              {/* Context badge: show matching sense when in sentence context */}
              {contextSense && (
                <div className="rounded-md border border-primary/20 bg-primary/5 px-2.5 py-1.5 text-sm">
                  <span className="text-xs text-muted-foreground">{t("wordCard.inContext")}</span>{" "}
                  <span className="font-medium text-primary">
                    {contextSense.native || contextSense.zh}
                  </span>
                  {locale !== "en" && contextSense.en && (
                    <span className="ml-1.5 text-xs text-muted-foreground">
                      {contextSense.en}
                    </span>
                  )}
                </div>
              )}

              {/* All senses (if multiple) */}
              {data.senses && data.senses.length > 0 ? (
                <div className="space-y-0.5">
                  {data.senses.map((s, i) => {
                    const isContext = contextSense && s.zh === contextSense.zh && s.en === contextSense.en;
                    const native = s.native || (locale === "en" ? s.en : s.zh);
                    return (
                      <div key={i} className="flex items-baseline gap-1.5 text-sm">
                        <span className="text-xs text-muted-foreground">{i + 1}.</span>
                        <span className={isContext ? "font-medium text-primary" : ""}>
                          {native}
                        </span>
                        {locale !== "en" && s.en && (
                          <span className="text-xs text-muted-foreground">{s.en}</span>
                        )}
                      </div>
                    );
                  })}
                </div>
              ) : (
                /* Fallback: single meaning (old cards without senses) */
                <div className="space-y-0.5">
                  {nativeMeaning && (
                    <p className="text-sm font-medium">{nativeMeaning}</p>
                  )}
                  {locale !== "en" && data.meaning_en && (
                    <p className="text-xs text-muted-foreground">{data.meaning_en}</p>
                  )}
                </div>
              )}

              {/* Plural form (noun) */}
              {pluralForm && (
                <p className="text-xs text-muted-foreground">
                  {t("wordCard.plural", { form: pluralForm })}
                </p>
              )}

              {/* Gender counterpart (animate nouns) */}
              {data.gender_counterpart?.word && (
                <p className="text-xs text-muted-foreground">
                  {data.gender === "féminin" ? t("wordCard.mascForm") : t("wordCard.femForm")}
                  {": "}
                  <button
                    onClick={() => handleFamilyWordClick(data.gender_counterpart!.word)}
                    className={`font-medium underline decoration-dotted underline-offset-2 hover:decoration-solid ${
                      data.gender_counterpart.gender === "masculin"
                        ? "text-blue-600 dark:text-blue-400"
                        : "text-rose-600 dark:text-rose-400"
                    }`}
                  >
                    {data.gender_counterpart.display}
                  </button>
                </p>
              )}

              {/* Word Family chips */}
              {data.word_family && (
                <WordFamilyChips
                  family={data.word_family}
                  currentWord={currentWord}
                  label={familyLabel!}
                  onWordClick={handleFamilyWordClick}
                />
              )}

              {/* Verb conjugation */}
              {isVerb && <VerbConjugation data={data} />}

              {/* Adjective forms */}
              {isAdj && data.adjective_forms && (
                <div>
                  <h4 className="mb-1 text-xs font-medium text-muted-foreground">{t("wordCard.adjForms")}</h4>
                  <div className="grid grid-cols-2 gap-1 text-xs">
                    <div className="rounded bg-muted/50 px-2 py-1">
                      <span className="text-muted-foreground">{t("wordCard.mascSg")} </span>
                      <span className="font-medium">{data.adjective_forms.masculine_singular}</span>
                    </div>
                    <div className="rounded bg-muted/50 px-2 py-1">
                      <span className="text-muted-foreground">{t("wordCard.femSg")} </span>
                      <span className="font-medium">{data.adjective_forms.feminine_singular}</span>
                    </div>
                    <div className="rounded bg-muted/50 px-2 py-1">
                      <span className="text-muted-foreground">{t("wordCard.mascPl")} </span>
                      <span className="font-medium">{data.adjective_forms.masculine_plural}</span>
                    </div>
                    <div className="rounded bg-muted/50 px-2 py-1">
                      <span className="text-muted-foreground">{t("wordCard.femPl")} </span>
                      <span className="font-medium">{data.adjective_forms.feminine_plural}</span>
                    </div>
                  </div>
                </div>
              )}

              {/* Examples */}
              {data.examples.length > 0 && (
                <div className="space-y-1.5">
                  <h4 className="text-xs font-medium text-muted-foreground">{t("wordCard.examples")}</h4>
                  {data.examples.map((ex, i) => {
                    // Resolve native text for this example
                    const exNative = ex.native
                      || (locale === "zh" ? ex.zh : null)
                      || (locale === "en" ? ex.en : null);

                    return (
                      <div key={i} className="rounded bg-muted/30 px-2 py-1.5 text-xs space-y-0.5">
                        <p className="italic text-foreground">{ex.fr}</p>
                        {/* English bridge (always shown) */}
                        {ex.en && (
                          <p className="text-muted-foreground">{ex.en}</p>
                        )}
                        {/* Native translation (only for non-EN users, when available) */}
                        {locale !== "en" && exNative && (
                          <p className="text-emerald-600 dark:text-emerald-400">{exNative}</p>
                        )}
                      </div>
                    );
                  })}
                </div>
              )}
            </>
          ) : null}
        </div>
      </PopoverContent>
    </Popover>
  );
}

/** Word family chip row */
function WordFamilyChips({
  family,
  currentWord,
  label,
  onWordClick,
}: {
  family: NonNullable<VocabularyCardData["word_family"]>;
  currentWord: string;
  label: string;
  onWordClick: (word: string) => void;
}) {
  return (
    <div className="rounded-md border border-border/50 bg-muted/20 px-2 py-1.5">
      <p className="text-[10px] font-medium text-muted-foreground mb-1">
        {label}
      </p>
      <div className="flex flex-wrap gap-1">
        {family.members.map((m) => {
          const isCurrent = m.word === currentWord;
          return (
            <button
              key={m.word}
              onClick={() => onWordClick(m.word)}
              title={`${m.display_full} — ${m.meaning_zh}`}
              className={`inline-flex items-center rounded px-1.5 py-0.5 text-[11px] transition-colors ${
                isCurrent
                  ? "bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300 font-semibold"
                  : "bg-muted/50 hover:bg-muted text-foreground/80 cursor-pointer"
              }`}
            >
              {m.display}
            </button>
          );
        })}
      </div>
    </div>
  );
}

/** Verb conjugation tabs */
function VerbConjugation({ data }: { data: VocabularyCardData }) {
  const t = useTranslations();
  const tenses: { key: string; label: string; table?: ConjugationTable }[] = [
    { key: "present", label: t("wordCard.tenses.present"), table: data.present },
    { key: "passe_compose", label: t("wordCard.tenses.passeCompose"), table: data.passe_compose },
    { key: "imparfait", label: t("wordCard.tenses.imparfait"), table: data.imparfait },
    { key: "futur_simple", label: t("wordCard.tenses.futurSimple"), table: data.futur_simple },
    { key: "conditionnel", label: t("wordCard.tenses.conditionnel"), table: data.conditionnel },
    { key: "subjonctif", label: t("wordCard.tenses.subjonctif"), table: data.subjonctif },
  ].filter((item) => item.table);

  if (tenses.length === 0) return null;

  return (
    <div>
      <div className="flex items-center gap-2 mb-1">
        <h4 className="text-xs font-medium text-muted-foreground">{t("wordCard.verbConj")}</h4>
        {data.verb_group && (
          <Badge variant="outline" className="text-[10px] px-1 py-0">
            {t("wordCard.verbGroup", { group: data.verb_group })}
          </Badge>
        )}
      </div>

      <Tabs defaultValue={tenses[0].key} className="w-full">
        <TabsList className="h-8 w-full justify-start gap-0.5 overflow-x-auto [&::-webkit-scrollbar]:hidden [-ms-overflow-style:none] [scrollbar-width:none]">
          {tenses.map((t) => (
            <TabsTrigger
              key={t.key}
              value={t.key}
              className="h-6 shrink-0 px-2 text-[11px]"
            >
              {t.label}
            </TabsTrigger>
          ))}
        </TabsList>
        {tenses.map((t) => (
          <TabsContent key={t.key} value={t.key} className="mt-1.5">
            <ConjugationGrid table={t.table!} />
          </TabsContent>
        ))}
      </Tabs>

      {/* Past participle + auxiliary */}
      {(data.past_participle || data.auxiliary) && (
        <div className="mt-1.5 flex gap-3 text-xs text-muted-foreground">
          {data.past_participle && (
            <span>
              {t("wordCard.pastParticiple", { form: data.past_participle })}
            </span>
          )}
          {data.auxiliary && (
            <span>
              {t("wordCard.auxiliary", { aux: data.auxiliary })}
            </span>
          )}
        </div>
      )}
    </div>
  );
}

/** Progressive loading messages for first-time word generation */
function WordCardLoading({ generating = false }: { generating?: boolean }) {
  const t = useTranslations();
  const messages = useMemo(
    () => [
      t("wordCard.loadMsg1"),
      t("wordCard.loadMsg2"),
      t("wordCard.loadMsg3"),
      t("wordCard.loadMsg4"),
      t("wordCard.loadMsg5"),
      t("wordCard.loadMsg6"),
    ],
    [t],
  );
  const [idx, setIdx] = useState(0);

  useEffect(() => {
    const delays = [4000, 5000, 7000, 9000, 15000];
    if (idx >= delays.length) return;
    const timer = setTimeout(() => setIdx((i) => i + 1), delays[idx]);
    return () => clearTimeout(timer);
  }, [idx]);

  return (
    <div className="flex flex-col items-center justify-center py-8 gap-3">
      <Loader2 className="h-6 w-6 animate-spin text-primary/60" />
      <p
        key={generating ? "gen" : idx}
        className="text-sm text-muted-foreground animate-in fade-in duration-500 text-center px-4"
      >
        {generating ? t("wordCard.generating") : messages[idx]}
      </p>
    </div>
  );
}

/** 2-column grid for a conjugation tense */
function ConjugationGrid({ table }: { table: ConjugationTable }) {
  const rows: [string, string][] = [
    ["je", "nous"],
    ["tu", "vous"],
    ["il", "ils"],
  ];

  return (
    <div className="grid grid-cols-2 gap-x-4 gap-y-1 text-[13px]">
      {rows.map(([left, right]) => (
        <div key={left} className="contents">
          <div>
            <span className="text-muted-foreground">{left} </span>
            <span className="font-medium">{table[left as keyof ConjugationTable] || "—"}</span>
          </div>
          <div>
            <span className="text-muted-foreground">{right} </span>
            <span className="font-medium">{table[right as keyof ConjugationTable] || "—"}</span>
          </div>
        </div>
      ))}
    </div>
  );
}
